name: DiscordChatBridge
version: ${project.version}
main: me.impurity.discordchatbridge.DiscordChatBridge
authors: [SevGay6]
description: Nigger gay discord plugin for impunity
website: lonearchy.uk.ms.to.ml.gov.edu.cumsexfartnigger
